### ISSUE TITLE
Wrong XHTML output for monospace

### ISSUE THREAD

**Issue by LarsGit223** [dokufreaks/plugin-creole#15]
Monospace now generates XHTML output like this:
```This is <code>monospace</code> text.```

According to the Creole specification the element **tt** should be used:
```This is <tt>monospace</tt> text.```

**Comment by LarsGit223** [comment]
The issue has been fixed. Now the **tt** element is used.

As the **tt** element doesn't look good with the DokuWiki default template a new config option ```'monospace'``` has been added to enable switching back to DokuWiki standard behaviour.

**Comment by selfthinker** [comment]
I was just made aware of this via splitbrain/dokuwiki#1657.
I would suggest to revert the fix for this. The Creole specification is **extremely old** for the web, it's from **2007**! `tt` was still a valid element back then but it isn't now. It was deprecated in HTML4.1 and removed in HTML5.

**Comment by LarsGit223** [comment]
Hmmm...would be OK for me.

Unfortunately there does not seem to be much progress on Creole 2.0. But there is a discussion on the usage of **tt** under http://wiki.wikicreole.org/Creole%202.0/Discussion#HTML5.

Any other opinions?
I will wait a week and if there are no concerns then I will revert the change.

**Comment by mikesteele81** [comment]
Dokuwiki's monospace (`''`) syntax seems to be meant for inline code fragments. It would be nice if creole's monospace (`##`) syntax applied a fixed-width font without any other typesetting changes. This is what the `<tt>` tag does, but the default font and size that gets chosen clashes with Dokuwiki's default template.

I agree with @selfthinker that as a quick fix it would be best to use the `<code>` tag.

**Comment by selfthinker** [comment]
> Dokuwiki's monospace (`''`) syntax seems to be meant for inline code fragments.

No, it is meant for "Monospaced Text", or at least that's what the description in the edit toolbar says (when you hover of the button). We had some discussions around that ages ago. I would have preferred to let it say "Code" (which it used to be in the beginning).

Regarding the Creole wiki comments:
> But that means that using the "semantic" HTML tags for that presentation is wrong -- because you are putting meanings on markup that didn't have them

Although that is sort of true, we're already doing that with other elements, like bold or italic. The code says it's strong and emphasised, not bold and italic.
That's why I would not use a `span` like the comments suggest. I understand that `code` is not always 100% semantically true but it is more true than anything else I can think of.
