### ISSUE TITLE
Wrong header level

### ISSUE THREAD

**Issue by filipefigcorreia** [dokufreaks/plugin-creole#8]
When I set the "Markup precedence" to "Creole" in the Admin panel,  headings on some "builtin pages" start appearing with the wrong level. H1 levels are being rendered as H5, it seems.

To reproduce this, go to a URL of a page that doesn't exist. A message "This topic does not exist yet" will be shown, and the title of the page will be redenred as H5 instead of H1.

**Comment by LarsGit223** [comment]
I reverted the change for this issue because the code was needed to resolve the ambiguity between DokuWiki and Creole heading syntax. Your issue can be fixed by changing the creole plugin configuration option **precedence** to **Creole**.

The problem is that the Creole syntax exists besides the DokuWiki syntax. And the heading syntax for both can be ambiguous.

Example level 1 heading in DokuWiki:
```====== Level 1 Heading ======```

Example level 1 heading in Creole:
```= Level 1 Heading =```

Example level 5 heading in DokuWiki:
```== Level 5 Heading ==```

Example level 5 heading in Creole:
```===== Level 5 =====```

To resolve this ambiguity there are two options:
- change the config settings as described above
- use Creole heading syntax like ```===== Level 5```. This does not conflict with the DokuWiki syntax.

**Comment by LarsGit223** [comment]
If you still got trouble with this issue, please re-open it.

**Comment by bmolitor** [comment]
What is meant, I think, is that DokuWiki still uses DokuWiki markup for internal means, for example the headings on the "page does not exist yet"/404-Page, the "admin" page, "configuration" page etc. If you set precedence to Creole, "internal" pages (which are still written in DokuWiki markup) are rendered as Creole, thus rendering top headings as H5 instead of H1 as intended. So, the fix is precisely the other way round:

* change markup **precedence** to **DokuWiki** to have the "internal" pages render correctly as DokuWiki markup, and then 
* edit your own pages to omit the closing =s in headings, so that these render correctly as Creole markup.

I don't see a good way for an "automatic fix" short of shipping replacement templates in creole for "internal" pages.
